openapi: "3.0.0"
info:
  version: 1.0.0
  title: Petstore
  description: A sample API for an internal tool in Nogginway
paths:
  /insurances:
    get:
      summary: Returns all insurances
      description: |
        Returns all insurances
      operationId: getInsurances
      responses:
        '200':
          description: insurance response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Insurance'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Insurance:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: Unique id of the insurance
        name:
          type: string
          description: Name of the insurance
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
